[package]
name = "virtual-company"
version = "2.0.0"
description = "Virtual Company desktop application"
authors = ["Kohzadi2023"]
edition = "2021"

[lib]
name = "virtual_company_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
