import {
  assessDecisionConsensus,
  decisionEvidenceForMessage,
  decisionVoteIdForMessage,
  findLatestDecisionProposal,
  parseSpecialistDecisionVote,
} from '@/lib/decisionVoting';
import { MEETING_FACILITATOR_AGENT_ID } from '@/lib/defaultCompany';
import { getRoomLanguage } from '@/lib/languages';
import { explicitItems, statedVerdicts, uniqueMessages } from '@/lib/meetingMinutes';
import { collectObjections } from '@/lib/objections';
import type { ActionItem, DecisionRecord, Message, Room, VoteChoice } from '@/types/domain';

/**
 * Printed at the top and bottom of every exported brief. Kept in English for
 * every room language: it is a legal notice, and a machine translation of it
 * would not be a reviewed text. Replace the wording once counsel has signed
 * off on it.
 */
export const BRIEF_DISCLAIMER = 'SIMULATION OUTPUT ONLY: This document is an automated synthesis generated by artificial intelligence models. It does not constitute professional legal, financial, architectural, or management consulting advice. The user bears sole responsibility for independent human verification before taking corporate or operational action.';

interface BriefLabels {
  title: string;
  decision: string;
  room: string;
  generated: string;
  summary: string;
  verdict: string;
  consensus: string;
  status: string;
  checklist: string;
  voters: string;
  matrix: string;
  matrixIntro: string;
  topic: string;
  positions: string;
  noTension: string;
  objectionsHeading: string;
  noObjections: string;
  verdictsHeading: string;
  raisedBy: string;
  objection: string;
  against: string;
  severity: string;
  finalVote: string;
  carriedHeading: string;
  carriedNote: string;
  dissents: string;
  noDissent: string;
  aiNote: string;
  conditions: string;
  actions: string;
  action: string;
  owner: string;
  deadline: string;
  priority: string;
  state: string;
  notAssigned: string;
  none: string;
  audit: string;
  auditNote: string;
  sourceMessages: string;
  participants: string;
  proposalAt: string;
  voter: string;
  role: string;
  vote: string;
  item: string;
  evidence: string;
  noProposal: string;
  noProposalNote: string;
  outcomes: Record<string, string>;
  consensusLabels: Record<'unanimous' | 'direction' | 'split' | 'incomplete', string>;
  statusLabels: Record<'proposed' | 'approved' | 'reversed' | 'unsynced', string>;
  choices: Record<VoteChoice, string>;
  checklistStatus: Record<'satisfied' | 'condition' | 'blocker', string>;
  checklistSummary: (satisfied: number, conditions: number, blockers: number) => string;
  tally: (agree: number, concern: number, disagree: number, abstain: number) => string;
}

const en: BriefLabels = {
  title: 'Executive Decision Brief',
  decision: 'Decision',
  room: 'Room',
  generated: 'Generated',
  summary: 'Executive Summary & Verdict',
  verdict: 'Verdict',
  consensus: 'Specialist consensus',
  status: 'Your ratification',
  checklist: 'Checklist',
  voters: 'Votes',
  matrix: 'Adversarial Matrix',
  matrixIntro: 'Topics where specialists stated different verdicts.',
  topic: 'Topic',
  positions: 'Positions',
  noTension: 'No topic with conflicting stated verdicts was found.',
  objectionsHeading: 'Objections raised in the critique round',
  noObjections: 'No structured objections were recorded. Specialists may have disagreed in prose only; the discussion itself is the record.',
  verdictsHeading: 'Conflicting stated verdicts',
  raisedBy: 'Raised by',
  objection: 'Objection',
  against: 'Against',
  severity: 'Severity',
  finalVote: 'Final vote',
  carriedHeading: 'Objections on record from specialists who then voted agree',
  carriedNote: 'The record does not show whether these were answered. Confirm each one before relying on the consensus.',
  dissents: 'Unresolved Minority Dissents',
  noDissent: 'No concern or disagreement was recorded.',
  aiNote: 'Every voter is an AI specialist persona, so agreement among them is not independent validation. Test the conclusion with a human before relying on it.',
  conditions: 'Conditions to satisfy',
  actions: 'Action Item Ledger',
  action: 'Action',
  owner: 'Owner',
  deadline: 'Deadline',
  priority: 'Priority',
  state: 'Status',
  notAssigned: 'Not assigned',
  none: 'None recorded.',
  audit: 'Audit Appendix',
  auditNote: 'Built locally from this room\'s recorded messages and votes. No AI was used to write this brief.',
  sourceMessages: 'Source messages',
  participants: 'Participants',
  proposalAt: 'Decision proposal recorded',
  voter: 'Voter',
  role: 'Role',
  vote: 'Vote',
  item: 'Item',
  evidence: 'Evidence',
  noProposal: 'No decision proposal recorded yet',
  noProposalNote: 'This is a draft built from the discussion only. Ask the facilitator for a decision proposal and collect the specialist votes to complete it.',
  outcomes: { GO: 'GO', NO_GO: 'NO-GO', CONDITIONAL_GO: 'CONDITIONAL GO', DEFER: 'DEFER' },
  consensusLabels: {
    unanimous: 'Unanimous',
    direction: 'Direction settled, concerns recorded',
    split: 'Split',
    incomplete: 'No votes recorded',
  },
  statusLabels: {
    proposed: 'Awaiting your ratification — specialist votes are advice, not approval',
    approved: 'Approved by you',
    reversed: 'Superseded by a later proposal',
    unsynced: 'Proposed, not yet registered as a decision',
  },
  choices: { agree: 'Agree', concern: 'Concern', disagree: 'Disagree', abstain: 'Abstain' },
  checklistStatus: { satisfied: 'Satisfied', condition: 'Condition', blocker: 'Blocker' },
  checklistSummary: (satisfied, conditions, blockers) => `satisfied ${satisfied} · conditions ${conditions} · blockers ${blockers}`,
  tally: (agree, concern, disagree, abstain) => `${agree} agree · ${concern} concern · ${disagree} disagree · ${abstain} abstain`,
};

const fa: BriefLabels = {
  title: 'گزارش اجرایی تصمیم',
  decision: 'تصمیم',
  room: 'اتاق',
  generated: 'تاریخ تهیه',
  summary: 'خلاصه اجرایی و حکم نهایی',
  verdict: 'حکم',
  consensus: 'اجماع متخصصان',
  status: 'تأیید شما',
  checklist: 'فهرست بررسی',
  voters: 'رأی‌ها',
  matrix: 'ماتریس تقابل نظرها',
  matrixIntro: 'موضوع‌هایی که متخصصان درباره‌شان حکم‌های متفاوت اعلام کرده‌اند.',
  topic: 'موضوع',
  positions: 'مواضع',
  noTension: 'موضوعی با حکم‌های متناقض پیدا نشد.',
  objectionsHeading: 'اعتراض‌های ثبت‌شده در دور نقد',
  noObjections: 'اعتراض ساخت‌یافته‌ای ثبت نشده است. شاید متخصصان فقط در متن مخالفت کرده‌اند؛ خود گفتگو سند است.',
  verdictsHeading: 'حکم‌های متناقض',
  raisedBy: 'مطرح‌کننده',
  objection: 'اعتراض',
  against: 'علیه',
  severity: 'شدت',
  finalVote: 'رأی نهایی',
  carriedHeading: 'اعتراض‌های ثبت‌شده از کسانی که بعداً موافق رأی دادند',
  carriedNote: 'سابقه نشان نمی‌دهد به این‌ها پاسخ داده شده یا نه. پیش از تکیه بر اجماع، هرکدام را بررسی کنید.',
  dissents: 'مخالفت‌های بدون پاسخ اقلیت',
  noDissent: 'هیچ نگرانی یا مخالفتی ثبت نشده است.',
  aiNote: 'همه‌ی رأی‌دهندگان شخصیت‌های هوش مصنوعی هستند؛ پس توافق آن‌ها اعتبارسنجی مستقل نیست. پیش از تکیه بر نتیجه، آن را با یک انسان بیازمایید.',
  conditions: 'شرط‌های لازم',
  actions: 'فهرست اقدام‌ها',
  action: 'اقدام',
  owner: 'مسئول',
  deadline: 'مهلت',
  priority: 'اولویت',
  state: 'وضعیت',
  notAssigned: 'تعیین نشده',
  none: 'موردی ثبت نشده است.',
  audit: 'پیوست ممیزی',
  auditNote: 'این گزارش به‌صورت محلی از پیام‌ها و رأی‌های ثبت‌شده‌ی همین اتاق ساخته شده است. برای نوشتن آن از هوش مصنوعی استفاده نشده است.',
  sourceMessages: 'تعداد پیام‌های منبع',
  participants: 'شرکت‌کنندگان',
  proposalAt: 'زمان ثبت پیشنهاد تصمیم',
  voter: 'رأی‌دهنده',
  role: 'نقش',
  vote: 'رأی',
  item: 'مورد',
  evidence: 'مستند',
  noProposal: 'هنوز پیشنهاد تصمیمی ثبت نشده است',
  noProposalNote: 'این فقط پیش‌نویسی از خود گفتگوست. برای تکمیل آن از مجری جلسه پیشنهاد تصمیم بخواهید و رأی متخصصان را جمع کنید.',
  outcomes: { GO: 'ادامه (GO)', NO_GO: 'توقف (NO-GO)', CONDITIONAL_GO: 'ادامه مشروط (CONDITIONAL GO)', DEFER: 'تعویق (DEFER)' },
  consensusLabels: {
    unanimous: 'اجماع کامل',
    direction: 'جهت مشخص است، نگرانی‌ها ثبت شده',
    split: 'اختلاف نظر',
    incomplete: 'رأیی ثبت نشده',
  },
  statusLabels: {
    proposed: 'در انتظار تأیید شما — رأی متخصصان مشورت است، نه تصویب',
    approved: 'توسط شما تأیید شده',
    reversed: 'با پیشنهاد بعدی جایگزین شده',
    unsynced: 'پیشنهاد شده، هنوز به‌عنوان تصمیم ثبت نشده',
  },
  choices: { agree: 'موافق', concern: 'نگران', disagree: 'مخالف', abstain: 'ممتنع' },
  checklistStatus: { satisfied: 'برآورده', condition: 'شرط', blocker: 'مانع' },
  checklistSummary: (satisfied, conditions, blockers) => `${satisfied} برآورده · ${conditions} شرط · ${blockers} مانع`,
  tally: (agree, concern, disagree, abstain) => `${agree} موافق · ${concern} نگران · ${disagree} مخالف · ${abstain} ممتنع`,
};

// Rooms in other languages fall back to English headings rather than shipping
// unreviewed translations of a document people will hand to clients.
const labelsByLanguage: Record<string, BriefLabels> = { en, fa };

const PRIORITY_ORDER: Record<ActionItem['priority'], number> = { high: 0, medium: 1, low: 2 };

/** A value safe to put in a Markdown table cell. */
function cell(value: string | undefined): string {
  return (value ?? '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
}

function authorLabel(message: Message): string {
  return message.authorNameSnapshot ?? 'Agent';
}

interface Voter {
  agentId: string;
  name: string;
  role: string;
  choice: VoteChoice;
  rationale: string;
  conditions: string[];
}

function collectVoters(room: Room, proposalMessageId: string): Voter[] {
  const proposalIndex = room.messages.findIndex(message => message.id === proposalMessageId);
  const recorded = room.votes?.find(vote => vote.id === decisionVoteIdForMessage(proposalMessageId))?.votes ?? {};
  const byAgent = new Map<string, Voter>();

  const identity = (agentId: string) => {
    const latest = [...room.messages].reverse().find(message => message.authorId === agentId);
    return { name: latest?.authorNameSnapshot ?? agentId, role: latest?.roleNameSnapshot ?? '' };
  };

  for (const [agentId, choice] of Object.entries(recorded)) {
    byAgent.set(agentId, { agentId, ...identity(agentId), choice, rationale: '', conditions: [] });
  }

  // The recorded tally only carries the choice; the reasoning lives in each
  // specialist's own vote message. A vote message that is newer than the
  // tally (not yet synced) still counts.
  for (const message of room.messages.slice(proposalIndex + 1)) {
    if (message.authorType !== 'agent' || !message.authorId || message.authorId === MEETING_FACILITATOR_AGENT_ID) continue;
    const parsed = parseSpecialistDecisionVote(message.content);
    if (!parsed) continue;
    const existing = byAgent.get(message.authorId);
    byAgent.set(message.authorId, {
      agentId: message.authorId,
      ...(existing ? { name: existing.name, role: existing.role } : identity(message.authorId)),
      choice: parsed.choice,
      rationale: parsed.rationale,
      conditions: parsed.conditions,
    });
  }
  return [...byAgent.values()];
}

function formatVerdictPositions(entries: { verdict: string; authors: string[] }[]): string {
  return entries.map(entry => `**${cell(entry.verdict)}** (${entry.authors.map(cell).join(', ')})`).join('; ');
}

function conflictingVerdicts(messages: readonly Message[]) {
  const bySubject = new Map<string, { subject: string; entries: { verdict: string; authors: string[] }[] }>();
  for (const item of statedVerdicts(messages)) {
    const key = item.subject.toLocaleLowerCase();
    const group = bySubject.get(key) ?? { subject: item.subject, entries: [] };
    group.entries.push({ verdict: item.verdict, authors: item.authors });
    bySubject.set(key, group);
  }
  return [...bySubject.values()].filter(group => group.entries.length > 1);
}

function actionRows(
  room: Room,
  actionItems: readonly ActionItem[],
  messages: readonly Message[],
  t: BriefLabels,
): string[] {
  const tracked = actionItems
    .filter(item => item.roomId === room.id)
    .sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority] || a.createdAt - b.createdAt);
  const known = new Set(tracked.map(item => item.title.trim().toLocaleLowerCase()));
  const spoken = [...new Set(messages.flatMap(message => explicitItems(message.content, 'action')))]
    .filter(title => !known.has(title.trim().toLocaleLowerCase()));

  return [
    ...tracked.map(item => `| ${cell(item.title)} | ${cell(item.owner) || t.notAssigned} | ${cell(item.deadline) || '—'} | ${item.priority} | ${item.status} |`),
    ...spoken.map(title => `| ${cell(title)} | ${t.notAssigned} | — | — | — |`),
  ];
}

export function buildExecutiveDecisionBrief(
  room: Room,
  decisionRecords: readonly DecisionRecord[] = [],
  actionItems: readonly ActionItem[] = [],
  now: Date = new Date(),
): string {
  const language = getRoomLanguage(room.languageCode);
  const t = labelsByLanguage[language.code] ?? en;
  const messages = uniqueMessages(room.messages);
  const record = findLatestDecisionProposal(room.messages);
  const proposal = record?.proposal;

  const voters = record ? collectVoters(room, record.message.id) : [];
  const counts: Record<VoteChoice, number> = { agree: 0, concern: 0, disagree: 0, abstain: 0 };
  for (const voter of voters) counts[voter.choice] += 1;
  const consensus = assessDecisionConsensus(
    Object.fromEntries(voters.map(voter => [voter.agentId, voter.choice])),
    voters.map(voter => voter.agentId),
  );

  const decision = record
    ? decisionRecords.find(item => item.roomId === room.id && item.evidence === decisionEvidenceForMessage(record.message.id))
    : undefined;
  const statusKey = decision ? decision.status : 'unsynced';

  const openChecklist = (proposal?.checklist ?? []).filter(item => item.status !== 'satisfied');
  const checklistCount = (status: 'satisfied' | 'condition' | 'blocker') => (proposal?.checklist ?? []).filter(item => item.status === status).length;

  const dissenters = voters.filter(voter => voter.choice === 'concern' || voter.choice === 'disagree');
  const voterConditions = voters.flatMap(voter => voter.conditions.map(condition => ({ from: voter.name, text: condition })));
  const tensions = conflictingVerdicts(messages);
  const objections = collectObjections(room.messages);
  const finalVoteOf = (agentId: string) => voters.find(voter => voter.agentId === agentId)?.choice;
  const rows = actionRows(room, actionItems, messages, t);
  const participants = new Set(messages.map(message => message.authorType === 'user' ? 'User' : authorLabel(message)));

  const lines: string[] = [
    `> ${BRIEF_DISCLAIMER}`,
    '',
    `# ${t.title}`,
    '',
    // Two trailing spaces are a Markdown hard break; without them the three lines merge into one paragraph.
    `**${t.decision}:** ${proposal?.title ?? t.noProposal}  `,
    `**${t.room}:** ${room.name}  `,
    `**${t.generated}:** ${now.toLocaleString()}`,
    '',
    `## 1. ${t.summary}`,
    '',
  ];

  if (proposal) {
    lines.push(
      `- **${t.verdict}:** ${t.outcomes[proposal.outcome] ?? proposal.outcome}`,
      `- **${t.consensus}:** ${t.consensusLabels[consensus.status]}${voters.length > 0 ? ` (${t.tally(counts.agree, counts.concern, counts.disagree, counts.abstain)})` : ''}`,
      `- **${t.status}:** ${t.statusLabels[statusKey]}`,
      `- **${t.checklist}:** ${t.checklistSummary(checklistCount('satisfied'), checklistCount('condition'), checklistCount('blocker'))}`,
      '',
      proposal.details,
    );
  } else {
    lines.push(`**${t.noProposal}.** ${t.noProposalNote}`);
  }

  lines.push('', `## 2. ${t.matrix}`, '', `### ${t.objectionsHeading}`, '');
  if (objections.length > 0) {
    lines.push(
      `| ${t.topic} | ${t.raisedBy} | ${t.severity} | ${t.objection} | ${t.against} | ${t.finalVote} |`,
      '| --- | --- | --- | --- | --- | --- |',
      ...objections.map(item => {
        const vote = finalVoteOf(item.agentId);
        return `| ${cell(item.topic)} | ${cell(item.role ? `${item.author} · ${item.role}` : item.author)} | ${item.severity} | ${cell(item.objection)} | ${cell(item.against) || '—'} | ${vote ? t.choices[vote] : '—'} |`;
      }),
    );
  } else {
    lines.push(`- ${t.noObjections}`);
  }
  lines.push('', `### ${t.verdictsHeading}`, '', t.matrixIntro, '');
  if (tensions.length > 0) {
    lines.push(
      `| ${t.topic} | ${t.positions} |`,
      '| --- | --- |',
      ...tensions.map(group => `| ${cell(group.subject)} | ${formatVerdictPositions(group.entries)} |`),
    );
  } else {
    lines.push(`- ${t.noTension}`);
  }

  lines.push('', `## 3. ${t.dissents}`, '');
  if (dissenters.length > 0) {
    for (const voter of dissenters) {
      const who = voter.role ? `${voter.name} · ${voter.role}` : voter.name;
      lines.push(`- **${who} — ${t.choices[voter.choice]}:** ${voter.rationale || '—'}`);
      for (const condition of voter.conditions) lines.push(`  - ${condition}`);
    }
  } else {
    lines.push(`- ${voters.length > 0 ? t.noDissent : t.none}`);
  }
  const carried = objections.filter(item => {
    const vote = finalVoteOf(item.agentId);
    return vote !== 'concern' && vote !== 'disagree';
  });
  if (carried.length > 0) {
    lines.push('', `### ${t.carriedHeading}`, '', t.carriedNote, '');
    for (const item of carried) {
      lines.push(`- **${item.author} — ${item.topic}** (${item.severity}): ${item.objection}`);
    }
  }
  if (voters.length > 0) lines.push('', `> ${t.aiNote}`);

  lines.push('', `## 4. ${t.actions}`, '');
  if (rows.length > 0) {
    lines.push(
      `| ${t.action} | ${t.owner} | ${t.deadline} | ${t.priority} | ${t.state} |`,
      '| --- | --- | --- | --- | --- |',
      ...rows,
    );
  } else {
    lines.push(`- ${t.none}`);
  }

  const conditionLines = [
    ...openChecklist.map(item => `- ${item.item} (${t.checklistStatus[item.status]})`),
    ...voterConditions.map(item => `- ${item.text} — ${item.from}`),
  ];
  if (conditionLines.length > 0) {
    lines.push('', `### ${t.conditions}`, '', ...[...new Set(conditionLines)]);
  }

  lines.push('', '---', '', `## ${t.audit}`, '', t.auditNote, '');
  lines.push(
    `- **${t.sourceMessages}:** ${room.messages.length}`,
    `- **${t.participants}:** ${participants.size}`,
  );
  if (record) lines.push(`- **${t.proposalAt}:** ${new Date(record.message.createdAt).toLocaleString()}`);

  if (voters.length > 0) {
    lines.push(
      '',
      `### ${t.voters}`,
      '',
      `| ${t.voter} | ${t.role} | ${t.vote} |`,
      '| --- | --- | --- |',
      ...voters.map(voter => `| ${cell(voter.name)} | ${cell(voter.role) || '—'} | ${t.choices[voter.choice]} |`),
    );
  }
  if (proposal && proposal.checklist.length > 0) {
    lines.push(
      '',
      `### ${t.checklist}`,
      '',
      `| ${t.item} | ${t.state} | ${t.evidence} |`,
      '| --- | --- | --- |',
      ...proposal.checklist.map(item => `| ${cell(item.item)} | ${t.checklistStatus[item.status]} | ${cell(item.evidence) || '—'} |`),
    );
  }

  lines.push('', '---', '', `> ${BRIEF_DISCLAIMER}`);
  return lines.join('\n');
}
